version: "3"

services:
  ##node_app##
  node_app:
    build: .
    command: npm run dev
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongo:
        condition: service_started
    volumes:
      - .:/app
    env_file:
      - .env

  ##RabbitMQ##
  rabbitmq:
    image: "rabbitmq:3.8.3-management"
    container_name: "rabbitmq"
    ports:
      - "15673:15672"
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
    env_file:
      - .env

  ##Mongo##
  mongo:
    image: "mongo:4.0"
    container_name: "mongo"
    ports:
      - "27018:27017"
